project:
  type: website

website:
  title: "birdie"
  navbar:
    left:
          - href: index.qmd
            text: Home
          - about.qmd
          - text: "Hands-on exercises"
            menu: 
            - text: "Hands-on exercise 1"
              href: "lessons/Hands-on/hands-on-2.qmd"
          - text: "In-class Exercise"
            menu: 
            - text: "In-class exercise 2"
              href: "lessons/in-class/in-class_02Ex02.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

