project:
  type: website

website:
  title: "IS415-GAA-HX"
  navbar:
    left:
          - href: index.qmd
            text: Home
          - about.qmd
          - text: "Hands-on exercises"
            menu: 
            - text: "Hands-on exercise 2"
              href: "lessons/Hands-on/Hands-on-Ex2/Hands-on-Ex2.html"
            - text: "Hands-on exercise 3"
              href: "lessons/Hands-on/Hands-on-Ex3/Hands-on-Ex3.html"
            - text: "Hands-on exercise 4"
              href: "lessons/Hands-on/Hands-on-Ex4/Hands-on-Ex4.html"
            - text: "Hands-on exercise 5"
              href: "lessons/Hands-on/Hands-on-Ex5/Hands-on-Ex5.html"
            - text: "Hands-on exercise 6"
              href: "lessons/Hands-on/Hands-on-Ex6/Hands-on-Ex6.html"
            - text: "Hands-on exercise 7"
              href: "lessons/Hands-on/Hands-on-Ex7/Hands-on-Ex7.html"
            
            
          - text: "In-class Exercise"
            menu: 
            - text: "In-class exercise 2"
              href: "lessons/In-class/in-class_ex2/In-class_Ex02.html"
            - text: "In-class exercise 3"
              href: "lessons/In-class/in-class_ex3/In-class_Ex03.html"
            - text: "In-class exercise 4"
              href: "lessons/In-class/in-class_ex4/In-class_Ex04.html"
            - text: "In-class exercise 5"
              href: "lessons/In-class/in-class_ex5/In-class_Ex05.html"
            - text: "In-class exercise 6"
              href: "lessons/In-class/in-class_ex6/In-class_Ex06.html"
          - text: "Take Home Exercise"
            menu: 
            - text: "Take Home Exercise 1"
              href: "lessons/Take-home/Take-home_ex1/Take-home_ex1.html"
            - text: "Take Home Exercise 2"
              href: "lessons/Take-home/Take-home_ex2/Take-home_ex2.html"

format:
  html:
    theme: Darkly
    css: styles.css
    toc: true

editor: visual

