project:
  type: website

website:
  title: "birdie"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      -text: "Hands on Excercise"
    menu:
    - text: "Hands-on excerise 1"
     href: 
    menu: 
    - text: "in-class excercise 2"
      href: lessons

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

