project:
  type: website

website:
  title: "IS415-GAA-HX"
  navbar:
    left:
          - href: index.qmd
            text: Home
          - about.qmd
          - text: "Hands-on exercises"
            menu: 
            - text: "Hands-on exercise 2"
              href: "lessons/Hands-on/Hands-on-Ex2/Hands-on-Ex2.qmd"
            - text: "Hands-on exercise 3"
              href: "lessons/Hands-on/Hands-on-Ex3/Hands-on-Ex3.qmd"
            - text: "Hands-on exercise 4"
              href: "lessons/Hands-on/Hands-on-Ex4/Hands-on-Ex4.qmd"
          - text: "In-class Exercise"
            menu: 
            - text: "In-class exercise 2"
              href: "lessons/In-class/in-class_ex2/In-class_Ex02.qmd"
            - text: "In-class exercise 3"
              href: "lessons/In-class/in-class_ex3/In-class_Ex03.qmd"
            - text: "In-class exercise 4"
              href: "lessons/In-class/in-class_ex4/In-class_Ex04.qmd"
          - text: "Take Home Exercise"
            menu: 
            - text: "Take Home Exercise 1"
              href: "lessons/Take-home/Take-home_ex1/Take-home_ex1.qmd"

format:
  html:
    theme: Darkly
    css: styles.css
    toc: true

editor: visual

