project:
  type: website

website:
  title: "IS415-GAA-HX"
  navbar:
    left:
          - href: index.qmd
            text: Home
          - about.qmd
          - text: "Hands-on exercises"
            menu: 
            - text: "Hands-on exercise 2"
              href: "lessons/Hands-on/Hands-on-Ex2/Hands-on-Ex2.qmd"
            - text: "Hands-on exercise 3"
              href: "lessons/Hands-on/Hands-on-Ex3/Hands-on-Ex3.qmd"
            - text: "Hands-on exercise 4"
              href: "lessons/Hands-on/Hands-on-Ex4/Hands-on-Ex4.qmd"
            - text: "Hands-on exercise 5"
              href: "lessons/Hands-on/Hands-on-Ex5/Hands-on-Ex5.qmd"
            - text: "Hands-on exercise 6"
              href: "lessons/Hands-on/Hands-on-Ex6/Hands-on-Ex6.qmd"
            - text: "Hands-on exercise 7"
              href: "lessons/Hands-on/Hands-on-Ex7/Hands-on-Ex7.qmd"
            - text: "Hands-on exercise 8"
              href: "lessons/Hands-on/Hands-on-Ex8/Hands-on-Ex8.qmd"    
            - text: "Hands-on exercise 9"
              href: "lessons/Hands-on/Hands-on-Ex9/Hands-on-Ex9.qmd"   
            - text: "Hands-on exercise 10"
              href: "lessons/Hands-on/Hands-on-Ex10/Hands-on-Ex10.qmd"   
            - text: "Hands-on exercise 11"
              href: "lessons/Hands-on/Hands-on-Ex11/Hands-on-Ex11.qmd"   
            - text: "Hands-on exercise 12"
              href: "lessons/Hands-on/Hands-on-Ex12/Hands-on-Ex12.qmd"         
        
          - text: "In-class Exercise"
            menu: 
            - text: "In-class exercise 2"
              href: "lessons/In-class/in-class_ex2/In-class_Ex02.qmd"
            - text: "In-class exercise 3"
              href: "lessons/In-class/in-class_ex3/In-class_Ex03.qmd"
            - text: "In-class exercise 4"
              href: "lessons/In-class/in-class_ex4/In-class_Ex04.qmd"
            - text: "In-class exercise 5"
              href: "lessons/In-class/in-class_ex5/In-class_Ex05.qmd"
            - text: "In-class exercise 6"
              href: "lessons/In-class/in-class_ex6/In-class_Ex06.qmd"
            - text: "In-class exercise 7"
              href: "lessons/In-class/in-class_ex7/In-class_Ex07.qmd"
            - text: "In-class exercise 8"
              href: "lessons/In-class/in-class_ex8/In-class_Ex08.qmd"
            - text: "In-class exercise 9"
              href: "lessons/In-class/in-class_ex9/In-class_Ex09.qmd"
            - text: "In-class exercise 10"
              href: "lessons/In-class/in-class_ex10/In-class_Ex10.qmd"
            - text: "In-class exercise 11"
              href: "lessons/In-class/in-class_ex11/In-class_Ex11.qmd"
            - text: "In-class exercise 12"
              href: "lessons/In-class/in-class_ex12/In-class_Ex12.qmd"
            
              
          - text: "Take Home Exercise"
            menu: 
            - text: "Take Home Exercise 1"
              href: "lessons/Take-home/Take-home_ex1/Take-home_ex1.qmd"
            - text: "Take Home Exercise 2"
              href: "lessons/Take-home/Take-home_ex2/Take-home_ex2.qmd"
            - text: "Take Home Exercise 3"
              href: "lessons/Take-home/Take-home_ex3/Take-home_eX3.qmd"              

          - text: "Shiny Workshop"
            menu: 
            - text: "Examples"
              href: "lessons/Workshop/Examples.html"

format:
  html:
    theme: Darkly
    css: styles.css
    toc: true

editor: visual

