---
title: "Take Home Exercise 3"
author: "Hao Xian"
date: "16 February 2023"
date-modified: `r Sys.Date()`
execute: 
  echo: true
  eval: true
  warning: true
  message: false

editor: visual
---

# Loading the Packages

```{r}
pacman::p_load(sf, tidyverse, tmap, spdep, 
             onemapsgapi, units, matrixStats, readxl, jsonlite,
             olsrr, corrplot, ggpubr, GWmodel,
             devtools, kableExtra, plotly, ggthemes)
```

# The Data

```{r}
rail_network_sf <- st_read(dsn="data/geospatial", layer="RapidTransitSystemStation")
```

```{r}
library(sf)
library(onemapsgapi)

token <- "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwMDA2LCJ1c2VyX2lkIjoxMDAwNiwiZW1haWwiOiJoeGNoZW4wMEBnbWFpbC5jb20iLCJmb3JldmVyIjpmYWxzZSwiaXNzIjoiaHR0cDpcL1wvb20yLmRmZS5vbmVtYXAuc2dcL2FwaVwvdjJcL3VzZXJcL3Nlc3Npb24iLCJpYXQiOjE2Nzg2MTIyOTYsImV4cCI6MTY3OTA0NDI5NiwibmJmIjoxNjc4NjEyMjk2LCJqdGkiOiJmNGY0ZWMxOTM0NzVjMGE5YTY0Mzg5Y2VkYjQ5MGE4ZCJ9.XxeiSlakErR5Pk88zYp1OZ7adGDgG7C7JSIGLECPuPA"
search_themes(token, "searchval")
get_theme_status(token, "themename")
themetibble <- get_theme(token, "themename")
themesf <- st_as_sf(themetibble, coords=c("Lng", "Lat"), crs=4326)
```
